### ISSUE TITLE
Error installing dependencies

### ISSUE THREAD

**Issue by sgujjaBebio** [hzi-bifo/epitope-prediction#9]
Hi,

I am getting this error when I install dependencies: Can you please help.

Thanks
Sharvari

```
pip3 install -r ./requirement/requirements.txt

      TypeError: str expected, not int
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by akashbahai** [comment]
Can you please tell me the Python version that you're using?

**Comment by sgujjaBebio** [comment]
Thank you for the reply. The python version I am using is:

Python 3.9.13

**Comment by akashbahai** [comment]
I am not sure why this error is popping up. Are you able to use pip directly to install a python package? If yes, it's possible that the version of your pip doesn't support the wheels for the packages in the requirement file.
I will suggest you to create a new conda environment with python version 3.6 or 3.7 and then try to install the required packages inside that environment.

```
conda create -n epitopevec python=3.7
conda activate epitopevec
pip install -r ./requirement/requirements.txt
```

**Comment by sgujjaBebio** [comment]
It seemed to fail towards the end:

```
Building wheels for collected packages: biopython, gensim
  Building wheel for biopython (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      running bdist_wheel
      running build
      running build_py
      Missing required dependency NumPy (Numerical Python).

      Unless running under Jython or IronPython, we require NumPy be installed
      when compiling Biopython. See http://www.numpy.org for details.

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for biopython
  Running setup.py clean for biopython
  Building wheel for gensim (setup.py) ... done
  Created wheel for gensim: filename=gensim-2.3.0-cp37-cp37m-macosx_10_9_x86_64.whl size=6207273 sha256=790e7e193c4b27fec488f24833e33c64ac9788a659adec0ed63d1cd3c735b174
  Stored in directory: /Users/shavarigujja/Library/Caches/pip/wheels/b1/bc/8a/0448f6a101b785a8c1867c80242aa708dc9a6438ad95bf3a45
Successfully built gensim
Failed to build biopython
```

**Comment by sgujjaBebio** [comment]
I tried installing the latest version of Biopython, and then rerunning the installation through the requirement.txt file, and it seemed to have installed the required version of Biopython. However, on running the main script, I get an error.

**ModuleNotFoundError: No module named 'Bio'**

```
pip install -r ./requirement/requirements.txt
Collecting numpy==1.17.1 (from -r ./requirement/requirements.txt (line 1))
  Using cached numpy-1.17.1-cp37-cp37m-macosx_10_9_x86_64.whl (15.0 MB)
Collecting scipy==1.4.1 (from -r ./requirement/requirements.txt (line 2))
  Using cached scipy-1.4.1-cp37-cp37m-macosx_10_6_intel.whl (28.4 MB)
Collecting matplotlib==3.1.3 (from -r ./requirement/requirements.txt (line 3))
  Using cached matplotlib-3.1.3-cp37-cp37m-macosx_10_9_x86_64.whl (13.2 MB)
Collecting scikit-learn==0.22.1 (from -r ./requirement/requirements.txt (line 4))
  Using cached scikit_learn-0.22.1-cp37-cp37m-macosx_10_6_intel.whl (11.0 MB)
Collecting biopython==1.71.0 (from -r ./requirement/requirements.txt (line 5))
  Using cached biopython-1.71.tar.gz (16.0 MB)
  Preparing metadata (setup.py) ... done
Collecting tqdm==4.15.0 (from -r ./requirement/requirements.txt (line 6))
  Using cached tqdm-4.15.0-py2.py3-none-any.whl (46 kB)
Collecting gensim==2.3.0 (from -r ./requirement/requirements.txt (line 7))
  Using cached gensim-2.3.0-cp37-cp37m-macosx_10_9_x86_64.whl
Collecting cycler>=0.10 (from matplotlib==3.1.3->-r ./requirement/requirements.txt (line 3))
  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting kiwisolver>=1.0.1 (from matplotlib==3.1.3->-r ./requirement/requirements.txt (line 3))
  Using cached kiwisolver-1.4.5-cp37-cp37m-macosx_10_9_x86_64.whl.metadata (6.4 kB)
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 (from matplotlib==3.1.3->-r ./requirement/requirements.txt (line 3))
  Using cached pyparsing-3.1.1-py3-none-any.whl.metadata (5.1 kB)
Collecting python-dateutil>=2.1 (from matplotlib==3.1.3->-r ./requirement/requirements.txt (line 3))
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting joblib>=0.11 (from scikit-learn==0.22.1->-r ./requirement/requirements.txt (line 4))
  Using cached joblib-1.3.2-py3-none-any.whl.metadata (5.4 kB)
Collecting six>=1.5.0 (from gensim==2.3.0->-r ./requirement/requirements.txt (line 7))
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting smart-open>=1.2.1 (from gensim==2.3.0->-r ./requirement/requirements.txt (line 7))
  Using cached smart_open-6.4.0-py3-none-any.whl.metadata (21 kB)
Collecting typing-extensions (from kiwisolver>=1.0.1->matplotlib==3.1.3->-r ./requirement/requirements.txt (line 3))
  Using cached typing_extensions-4.7.1-py3-none-any.whl.metadata (3.1 kB)
Using cached joblib-1.3.2-py3-none-any.whl (302 kB)
Using cached kiwisolver-1.4.5-cp37-cp37m-macosx_10_9_x86_64.whl (67 kB)
Using cached pyparsing-3.1.1-py3-none-any.whl (103 kB)
Using cached smart_open-6.4.0-py3-none-any.whl (57 kB)
Using cached typing_extensions-4.7.1-py3-none-any.whl (33 kB)
Building wheels for collected packages: biopython
  Building wheel for biopython (setup.py) ... done
  Created wheel for biopython: filename=biopython-1.71-cp37-cp37m-macosx_10_9_x86_64.whl size=2022225 sha256=2aaed39d268525b2d66658821c1c7dfb1a01e775faf22038bb0b4cf73845de77
  Stored in directory: /Users/shavarigujja/Library/Caches/pip/wheels/48/85/4b/a9c428fb719da72b6c4c69c85d422b019becd050358f1ff3e4
Successfully built biopython
Installing collected packages: tqdm, typing-extensions, smart-open, six, pyparsing, numpy, joblib, cycler, scipy, python-dateutil, kiwisolver, biopython, scikit-learn, matplotlib, gensim
  Attempting uninstall: numpy
    Found existing installation: numpy 1.21.6
    Uninstalling numpy-1.21.6:
      Successfully uninstalled numpy-1.21.6
  Attempting uninstall: biopython
    Found existing installation: biopython 1.81
    Uninstalling biopython-1.81:
      Successfully uninstalled biopython-1.81
Successfully installed biopython-1.71 cycler-0.11.0 gensim-2.3.0 joblib-1.3.2 kiwisolver-1.4.5 matplotlib-3.1.3 numpy-1.17.1 pyparsing-3.1.1 python-dateutil-2.8.2 scikit-learn-0.22.1 scipy-1.4.1 six-1.16.0 smart-open-6.4.0 tqdm-4.15.0 typing-extensions-4.7.1
(epitopevec) shavarigujja@MBP-SGUJJA-106732 epitope-prediction %  python3 main.py -h
Traceback (most recent call last):
  File "/Users/shavarigujja/projects/immunogenecity_pred_tools/epitope-prediction/main.py", line 2, in <module>
    import score_fasta
  File "/Users/shavarigujja/projects/immunogenecity_pred_tools/epitope-prediction/score_fasta.py", line 1, in <module>
    from Bio import SeqIO
ModuleNotFoundError: No module named 'Bio'
(epitopevec) shavarigujja@MBP-SGUJJA-106732 epitope-prediction % pip list
Package           Version
----------------- -------
biopython         1.71
cycler            0.11.0
gensim            2.3.0
joblib            1.3.2
kiwisolver        1.4.5
matplotlib        3.1.3
numpy             1.17.1
pip               23.3.1
pyparsing         3.1.1
python-dateutil   2.8.2
scikit-learn      0.22.1
scipy             1.4.1
setuptools        68.2.2
six               1.16.0
smart-open        6.4.0
tqdm              4.15.0
typing_extensions 4.7.1
wheel             0.42.0
```

**Comment by sgujjaBebio** [comment]
```
pip install gensim==3.7.3
pip install ./requirement/pydpi-1.0.tar.gz
```
It seems to be working now after running the above code.

**Comment by akashbahai** [comment]
Thanks for trying the method. I am glad that it's working for you now.
